// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ODataExample.EntityFramework;

namespace ODataExample.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20190330152921_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("ODataExample.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("ISBN");

                    b.Property<int?>("PressId");

                    b.Property<decimal>("Price");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("PressId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("ODataExample.Entities.Press", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Presses");
                });

            modelBuilder.Entity("ODataExample.Entities.Book", b =>
                {
                    b.HasOne("ODataExample.Entities.Press", "Press")
                        .WithMany()
                        .HasForeignKey("PressId");

                    b.OwnsOne("ODataExample.Entities.Address", "Location", b1 =>
                        {
                            b1.Property<int>("BookId");

                            b1.Property<string>("City");

                            b1.Property<string>("Street");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.HasOne("ODataExample.Entities.Book")
                                .WithOne("Location")
                                .HasForeignKey("ODataExample.Entities.Address", "BookId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
